services:
  - type: web
    name: pdf-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "pdf:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 